### ISSUE TITLE
Coordinates out of range

### ISSUE THREAD

**Issue by meuep** [cmonr/Eagle-ULPs#3]
Followed the steps to create the svg file (made sure it was plain, converted everything to a path, etc..) but received several errors when running svg2poly within eagle - a number of them all resembling the format "Coordinates ([some number], [some number]) are out of range! Maximum allowed range is +/- 78.74015748 inch".

Perhaps it's user error when I was setting up the svg file to begin with, but I tried a dozen times to make the svg bigger/smaller (starting off setting the height to 100 px) with no luck. Am I causing the problem somehow? if not perhaps this is an issue?

Eagle version 7.1.0 Standard
Inkscape version 0.48

**Comment by a3ng7n** [comment]
Thank you for the quick response! I'll give this a shot.

**Comment by Dirk67** [comment]
I tried with Eagle 6.6.0
but can get no good results...
maybe a user error (I am a beginner with SVG) ?

 - here is the original logo --> http://24max.de/temp/Pb-free.bmp
 - here is the svg-file I generated 
      from this bitmap (with inkscape) --> http://24max.de/temp/no_pb_logo3.svg
 - here is the weird result in eagle --> http://24max.de/temp/result.png

what am I doing wrong ?

b.t.w.
 is it compatible with EAGLE 7.x.x in the meantime ?

**Comment by cmonr** [comment]
@Dirk67 I've moved your error to a separate issue. I'll be closing this one since it's stale.
